# Configuration for Google OAuth2

security:
  oauth2:
    client:
      clientId: ${com.google.clientId}
      clientSecret: ${com.google.clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false


# Turn on this logging for troubleshooting
#logging:
#  level:
#    org.springframework.security: DEBUG